---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-pv-volume
  labels:
    type: local
spec:
  storageClassName: mysqlstorageclass
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/Users/bryanalonso/datapath/analisis-datos-python/proyecto/storage_mysql"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pv-claim
spec:
  storageClassName: mysqlstorageclass
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi